### ISSUE TITLE
How Adding Rewards

### ISSUE THREAD

**Issue by xDarkSaintx** [LDX-MCPE/VoteReward#25]
I need Creative Rewards for my server .. But I don't know how to put it .. Cuz I'm new in Pocketmine

**Comment by LukeDarling** [comment]
Please be more specific. What do you mean by creative rewards?

**Comment by xDarkSaintx** [comment]
I mean .. when You vote .. U got Creative mode Reward

**Comment by xDarkSaintx** [comment]
``` yaml
# Config file for VoteReward by LDX.

# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists

# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "The player &e{NICKNAME}&r voted with &b/vote&r and got cool rewards!"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "264:0:20"
  - "265:0:15"
  - "266:0:15"

# List of commands to execute when a player votes.
Commands:
  - "particle portal {X} {Y1} {Z} 2 2 2 10000"
  - "gamemode 1{USERNAME}"
```
